package dev.gaddal.core.presentation.designsystem.colors

import androidx.compose.ui.graphics.Color

val nature_calm_light_primary = Color(0xFF036D33)
val nature_calm_light_onPrimary = Color(0xFFFFFFFF)
val nature_calm_light_primaryContainer = Color(0xFF9BF7AD)
val nature_calm_light_onPrimaryContainer = Color(0xFF00210B)
val nature_calm_light_secondary = Color(0xFF016D38)
val nature_calm_light_onSecondary = Color(0xFFFFFFFF)
val nature_calm_light_secondaryContainer = Color(0xFF9BF6B2)
val nature_calm_light_onSecondaryContainer = Color(0xFF00210D)
val nature_calm_light_tertiary = Color(0xFF006D43)
val nature_calm_light_onTertiary = Color(0xFFFFFFFF)
val nature_calm_light_tertiaryContainer = Color(0xFF91F7BD)
val nature_calm_light_onTertiaryContainer = Color(0xFF002111)
val nature_calm_light_error = Color(0xFFBA1A1A)
val nature_calm_light_errorContainer = Color(0xFFFFDAD6)
val nature_calm_light_onError = Color(0xFFFFFFFF)
val nature_calm_light_onErrorContainer = Color(0xFF410002)
val nature_calm_light_background = Color(0xFFFCFDF7)
val nature_calm_light_onBackground = Color(0xFF191C19)
val nature_calm_light_surface = Color(0xFFFCFDF7)
val nature_calm_light_onSurface = Color(0xFF191C19)
val nature_calm_light_surfaceVariant = Color(0xFFDDE5DA)
val nature_calm_light_onSurfaceVariant = Color(0xFF414941)
val nature_calm_light_outline = Color(0xFF717970)
val nature_calm_light_inverseOnSurface = Color(0xFFF0F1EC)
val nature_calm_light_inverseSurface = Color(0xFF2E312E)
val nature_calm_light_inversePrimary = Color(0xFF80DA93)
val nature_calm_light_shadow = Color(0xFF000000)
val nature_calm_light_surfaceTint = Color(0xFF036D33)
val nature_calm_light_outlineVariant = Color(0xFFC1C9BE)
val nature_calm_light_scrim = Color(0xFF000000)

val nature_calm_dark_primary = Color(0xFF80DA93)
val nature_calm_dark_onPrimary = Color(0xFF003917)
val nature_calm_dark_primaryContainer = Color(0xFF005225)
val nature_calm_dark_onPrimaryContainer = Color(0xFF9BF7AD)
val nature_calm_dark_secondary = Color(0xFF80D998)
val nature_calm_dark_onSecondary = Color(0xFF00391A)
val nature_calm_dark_secondaryContainer = Color(0xFF005228)
val nature_calm_dark_onSecondaryContainer = Color(0xFF9BF6B2)
val nature_calm_dark_tertiary = Color(0xFF75DAA2)
val nature_calm_dark_onTertiary = Color(0xFF003921)
val nature_calm_dark_tertiaryContainer = Color(0xFF005232)
val nature_calm_dark_onTertiaryContainer = Color(0xFF91F7BD)
val nature_calm_dark_error = Color(0xFFFFB4AB)
val nature_calm_dark_errorContainer = Color(0xFF93000A)
val nature_calm_dark_onError = Color(0xFF690005)
val nature_calm_dark_onErrorContainer = Color(0xFFFFDAD6)
val nature_calm_dark_background = Color(0xFF191C19)
val nature_calm_dark_onBackground = Color(0xFFE2E3DE)
val nature_calm_dark_surface = Color(0xFF191C19)
val nature_calm_dark_onSurface = Color(0xFFE2E3DE)
val nature_calm_dark_surfaceVariant = Color(0xFF414941)
val nature_calm_dark_onSurfaceVariant = Color(0xFFC1C9BE)
val nature_calm_dark_outline = Color(0xFF8B9389)
val nature_calm_dark_inverseOnSurface = Color(0xFF191C19)
val nature_calm_dark_inverseSurface = Color(0xFFE2E3DE)
val nature_calm_dark_inversePrimary = Color(0xFF036D33)
val nature_calm_dark_shadow = Color(0xFF000000)
val nature_calm_dark_surfaceTint = Color(0xFF80DA93)
val nature_calm_dark_outlineVariant = Color(0xFF414941)
val nature_calm_dark_scrim = Color(0xFF000000)


val nature_calm_seed = Color(0xFF006C32)
