package dev.gaddal.core.presentation.designsystem.colors

import androidx.compose.ui.graphics.Color

val sky_high_light_primary = Color(0xFF006685)
val sky_high_light_onPrimary = Color(0xFFFFFFFF)
val sky_high_light_primaryContainer = Color(0xFFBEE9FF)
val sky_high_light_onPrimaryContainer = Color(0xFF001F2A)
val sky_high_light_secondary = Color(0xFF006685)
val sky_high_light_onSecondary = Color(0xFFFFFFFF)
val sky_high_light_secondaryContainer = Color(0xFFBEE9FF)
val sky_high_light_onSecondaryContainer = Color(0xFF001F2A)
val sky_high_light_tertiary = Color(0xFF00687A)
val sky_high_light_onTertiary = Color(0xFFFFFFFF)
val sky_high_light_tertiaryContainer = Color(0xFFADECFF)
val sky_high_light_onTertiaryContainer = Color(0xFF001F26)
val sky_high_light_error = Color(0xFFBA1A1A)
val sky_high_light_errorContainer = Color(0xFFFFDAD6)
val sky_high_light_onError = Color(0xFFFFFFFF)
val sky_high_light_onErrorContainer = Color(0xFF410002)
val sky_high_light_background = Color(0xFFFBFCFE)
val sky_high_light_onBackground = Color(0xFF191C1E)
val sky_high_light_surface = Color(0xFFFBFCFE)
val sky_high_light_onSurface = Color(0xFF191C1E)
val sky_high_light_surfaceVariant = Color(0xFFDCE4E9)
val sky_high_light_onSurfaceVariant = Color(0xFF40484C)
val sky_high_light_outline = Color(0xFF70787D)
val sky_high_light_inverseOnSurface = Color(0xFFF0F1F3)
val sky_high_light_inverseSurface = Color(0xFF2E3133)
val sky_high_light_inversePrimary = Color(0xFF6AD3FF)
val sky_high_light_shadow = Color(0xFF000000)
val sky_high_light_surfaceTint = Color(0xFF006685)
val sky_high_light_outlineVariant = Color(0xFFC0C8CD)
val sky_high_light_scrim = Color(0xFF000000)

val sky_high_dark_primary = Color(0xFF6AD3FF)
val sky_high_dark_onPrimary = Color(0xFF003546)
val sky_high_dark_primaryContainer = Color(0xFF004D65)
val sky_high_dark_onPrimaryContainer = Color(0xFFBEE9FF)
val sky_high_dark_secondary = Color(0xFF6AD3FF)
val sky_high_dark_onSecondary = Color(0xFF003546)
val sky_high_dark_secondaryContainer = Color(0xFF004D65)
val sky_high_dark_onSecondaryContainer = Color(0xFFBEE9FF)
val sky_high_dark_tertiary = Color(0xFF56D6F5)
val sky_high_dark_onTertiary = Color(0xFF003640)
val sky_high_dark_tertiaryContainer = Color(0xFF004E5D)
val sky_high_dark_onTertiaryContainer = Color(0xFFADECFF)
val sky_high_dark_error = Color(0xFFFFB4AB)
val sky_high_dark_errorContainer = Color(0xFF93000A)
val sky_high_dark_onError = Color(0xFF690005)
val sky_high_dark_onErrorContainer = Color(0xFFFFDAD6)
val sky_high_dark_background = Color(0xFF191C1E)
val sky_high_dark_onBackground = Color(0xFFE1E2E5)
val sky_high_dark_surface = Color(0xFF191C1E)
val sky_high_dark_onSurface = Color(0xFFE1E2E5)
val sky_high_dark_surfaceVariant = Color(0xFF40484C)
val sky_high_dark_onSurfaceVariant = Color(0xFFC0C8CD)
val sky_high_dark_outline = Color(0xFF8A9297)
val sky_high_dark_inverseOnSurface = Color(0xFF191C1E)
val sky_high_dark_inverseSurface = Color(0xFFE1E2E5)
val sky_high_dark_inversePrimary = Color(0xFF006685)
val sky_high_dark_shadow = Color(0xFF000000)
val sky_high_dark_surfaceTint = Color(0xFF6AD3FF)
val sky_high_dark_outlineVariant = Color(0xFF40484C)
val sky_high_dark_scrim = Color(0xFF000000)


val sky_high_seed = Color(0xFF0CB0E1)
